import { Router } from 'express';
import authRoutes from './auth.routes';
import contactRoutes from './contact.routes';
import coursesRoutes from './courses.routes';
import mentorsRoutes from './mentors.routes';
import partnersRoutes from './partners.routes';
import enrollmentsRoutes from './enrollments.routes';
import blogRoutes from './blog.routes';
import adminRoutes from './admin.routes';
import usersRoutes from './users.routes';
import { lessonsRouter, modulesRouter } from './curriculum.routes';
import progressRoutes from './progress.routes';
import sessionsRoutes from './sessions.routes';
import uploadsRoutes from './uploads.routes';
import { mentorRequestsRouter, questionsRouter } from './questions.routes';
import { announcementsRouter, notificationsRouter } from './notifications.routes';
import siteSettingsRoutes from './siteSettings.routes';
import testimonialsRoutes from './testimonials.routes';
import courseReviewsRoutes from './courseReviews.routes';
import projectsRoutes from './projects.routes';
import { verifyCertificateHandler } from '../controllers/enrollments.controller';

const router = Router();

router.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' } }));
// Ochiq sertifikat tekshiruvi — ish beruvchilar uchun, login talab qilinmaydi
router.get('/certificates/:no/verify', verifyCertificateHandler);
router.use('/auth', authRoutes);
router.use('/contact', contactRoutes);
router.use('/courses', coursesRoutes);
router.use('/mentors', mentorsRoutes);
router.use('/partners', partnersRoutes);
router.use('/enrollments', enrollmentsRoutes);
router.use('/blog', blogRoutes);
router.use('/admin', adminRoutes);
router.use('/users', usersRoutes);
router.use('/modules', modulesRouter);
router.use('/lessons', lessonsRouter);
router.use('/progress', progressRoutes);
router.use('/sessions', sessionsRoutes);
router.use('/uploads', uploadsRoutes);
router.use('/questions', questionsRouter);
router.use('/mentor-requests', mentorRequestsRouter);
router.use('/notifications', notificationsRouter);
router.use('/announcements', announcementsRouter);
router.use('/site-settings', siteSettingsRoutes);
router.use('/testimonials', testimonialsRoutes);
router.use('/reviews', courseReviewsRoutes);
router.use('/projects', projectsRoutes);

export default router;
